/**
 * Mixed this 2 apis:
 * Find all admin areas in TW http://dataservice.accuweather.com/locations/v1/adminareas/{TW}
 * Find the (Location)Key: http://dataservice.accuweather.com/locations/v1/cities/autocomplete
 */

export const availableLocations: {
  ID: string;
  Key: string;
  LocalizedName: string;
  EnglishName: string;
  Level: number;
  LocalizedType: string;
  EnglishType: string;
  CountryID: string;
}[] = [
  {
    ID: "CHA",
    Key: "3369300",
    LocalizedName: "Changhua",
    EnglishName: "Changhua",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
  {
    ID: "CYI",
    Key: "312591",
    LocalizedName: "Chiayi City",
    EnglishName: "Chiayi City",
    Level: 1,
    LocalizedType: "Municipality",
    EnglishType: "Municipality",
    CountryID: "TW",
  },
  {
    ID: "CYQ",
    Key: "3369303",
    LocalizedName: "Chiayi",
    EnglishName: "Chiayi",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
  {
    ID: "HSQ",
    Key: "3369298",
    LocalizedName: "Hsinchu",
    EnglishName: "Hsinchu",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
  {
    ID: "HSZ",
    Key: "313567",
    LocalizedName: "Hsinchu City",
    EnglishName: "Hsinchu City",
    Level: 1,
    LocalizedType: "Municipality",
    EnglishType: "Municipality",
    CountryID: "TW",
  },
  {
    ID: "HUA",
    Key: "3369306",
    LocalizedName: "Hualien",
    EnglishName: "Hualien",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
  {
    ID: "ILA",
    Key: "58894",
    LocalizedName: "Yilan",
    EnglishName: "Yilan",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
  {
    ID: "KEE",
    Key: "312605",
    LocalizedName: "Keelung City",
    EnglishName: "Keelung City",
    Level: 1,
    LocalizedType: "Municipality",
    EnglishType: "Municipality",
    CountryID: "TW",
  },
  {
    ID: "KHH",
    Key: "313812",
    LocalizedName: "Kaohsiung City",
    EnglishName: "Kaohsiung City",
    Level: 1,
    LocalizedType: "Special Municipality",
    EnglishType: "Special Municipality",
    CountryID: "TW",
  },
  {
    ID: "KIN",
    Key: "2332525",
    LocalizedName: "Kinmen",
    EnglishName: "Kinmen",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
  {
    ID: "LIE",
    Key: "3369309",
    LocalizedName: "Lienchiang",
    EnglishName: "Lienchiang",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
  {
    ID: "MIA",
    Key: "3369299",
    LocalizedName: "Miaoli",
    EnglishName: "Miaoli",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
  {
    ID: "NAN",
    Key: "3369301",
    LocalizedName: "Nantou",
    EnglishName: "Nantou",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
  {
    ID: "NWT",
    Key: "2515397",
    LocalizedName: "New Taipei City",
    EnglishName: "New Taipei City",
    Level: 1,
    LocalizedType: "Special Municipality",
    EnglishType: "Special Municipality",
    CountryID: "TW",
  },
  {
    ID: "PEN",
    Key: "3369307",
    LocalizedName: "Penghu",
    EnglishName: "Penghu",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
  {
    ID: "PIF",
    Key: "3369304",
    LocalizedName: "Pingtung",
    EnglishName: "Pingtung",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
  {
    ID: "TAO",
    Key: "3369297",
    LocalizedName: "Taoyuan City",
    EnglishName: "Taoyuan City",
    Level: 1,
    LocalizedType: "Special Municipality",
    EnglishType: "Special Municipality",
    CountryID: "TW",
  },
  {
    ID: "TNN",
    Key: "314999",
    LocalizedName: "Tainan City",
    EnglishName: "Tainan City",
    Level: 1,
    LocalizedType: "Special Municipality",
    EnglishType: "Special Municipality",
    CountryID: "TW",
  },
  {
    ID: "TPE",
    Key: "315078",
    LocalizedName: "Taipei City",
    EnglishName: "Taipei City",
    Level: 1,
    LocalizedType: "Special Municipality",
    EnglishType: "Special Municipality",
    CountryID: "TW",
  },
  {
    ID: "TTT",
    Key: "3369305",
    LocalizedName: "Taitung",
    EnglishName: "Taitung",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
  {
    ID: "TXG",
    Key: "315040",
    LocalizedName: "Taichung City",
    EnglishName: "Taichung City",
    Level: 1,
    LocalizedType: "Special Municipality",
    EnglishType: "Special Municipality",
    CountryID: "TW",
  },
  {
    ID: "YUN",
    Key: "3369302",
    LocalizedName: "Yunlin",
    EnglishName: "Yunlin",
    Level: 1,
    LocalizedType: "County",
    EnglishType: "County",
    CountryID: "TW",
  },
];
